from typing import Dict

class SymbolMapper:
    """
    Utility to map NSE symbols to ICICI Breeze Stock Codes.
    """
    
    # Common Nifty constituent mismatches [cite: 59]
    _NSE_TO_BREEZE = {
        "RELIANCE": "RELIND",
        "HDFCBANK": "HDFBAN",
        "ICICIBANK": "ICIBAN",
        "BAJAJFINSV": "BAJFNS",
        "BAJFINANCE": "BAJFI",
        "KOTAKBANK": "KOTMAH",
        "NATIONALUM": "NATALU",
        "M&M": "MAHMAH",
        "L&T": "LANTUF",
        "HCLTECH": "HCLTEC",
        "SUNPHARMA": "SUNPHA",
        "DRREDDY": "DRREDD",
        "BHARTIARTL": "BHAART",
        "ADANIPORTS": "ADAPOR",
        "ADANIENT": "ADAENT",
        "COALINDIA": "COALIN",
        "JSWSTEEL": "JSWSTE",
        "TATASTEEL": "TATSTE",
        "POWERGRID": "POWGRI",
        "TITAN": "TITAN",
        "ULTRACEMCO": "ULTCEM",
        "NTPC": "NTPC",
        "ITC": "ITC",
        "ASIANPAINT": "ASIPAI",
        "HINDALCO": "HINDAL",
        "SBIN": "SBIN",
        "HINDUNILVR": "HINLEV",
        "INFY": "INFTEC",
        "TCS": "TCS",
        "AXISBANK": "AXIBAN",
        "MARUTI": "MARUTI",
        "INDUSINDBK": "INDBAN",
        "BAJAJ-AUTO": "BAAUTO",
        "WIPRO": "WIPRO",
        "APOLLOHOSP": "APOHOS",
        "EICHERMOT": "EICMOT",
        "HEROMOTOCO": "HERHON",
        "BPCL": "BPCL",
        "ONGC": "ONGC",
        "ADANIPOWER": "ADAPOW",
        "TATAELXSI": "TATAEL",
        "POLYCAB": "POLYCAB",
        "PATANJALI": "PATANJ",
        "SHREECEM": "SHRCEM",
        "CHOLAFIN": "CHOFIN",
        "MOTHERSON": "SAMMOT",
        "GAIL": "GAIL",
        "MFSL": "MAXFIN",
        "DEEPAKFERT": "DEEFER",
        "BAJAJHLDNG": "BAJHLD",
        "HDFCAMC": "HDFAMC",
        "IDBI": "IDBIBANK",
        "FORCEMOT": "FORMOT",
        "FORTIS": "FORHEA",
        "FIVESTAR": "FIVEST",
        "OIL": "OILIND",
        "ITI": "ITI",
        "PIRAMALFIN": "PIRENT",
        "PPLPHARMA": "PPLPHA",
        "SIEMENS": "SIEMEN",
        "IRCTC": "IRCTC",
        "LTF": "L&TFH",
        "HYUNDAI": "HYUNDA",
        "EXIDEIND": "EXIIND",
        "ANGELONE": "ANGELONE",
        "COFORGE": "NIITEC",
        "TATACONSUM": "TATGLO",
        "ASTERDM": "ASTHEA",
        "INDHOTEL": "INDHOT",
        "BANDHANBNK": "BANBNK",
        "JBMA": "JBMA",
        "HINDZINC": "HINZIN",
        "DATAPATTNS": "DATPAT",
        "KPITTECH": "KPITEC",
        "RECLTD": "RECLTD",
        "FEDERALBNK": "FEDBNK",
        "BRIGADE": "BRIENT",
        "SWANCORP": "SWANEN",
        "DLF": "DLF",
        "LAURUSLABS": "LAULAB",
        "JIOFIN": "JIOFIN",
        "NESTLEIND": "NESIND",
        "AARTIIND": "AARIND",
        "LICHSGFIN": "LICHFL",
        "KALYANKJIL": "KALKJU",
        "HBLENGINE": "HBLPOW",
        "GODREJCP": "GODCP",
        "ICICIGI": "ICIGEN",
        "MANAPPURAM": "MANFIN",
        "UPL": "UPL",
        "VOLTAS": "VOLTAS",
        "FSL": "FSL",
        "GMDCLTD": "GUJMIN",
        "MUTHOOTFIN": "MUTFIN",
        "IFCI": "IFCI",
        "BLS": "BLS",
        "TORNTPHARM": "TORPHA",
        "CDSL": "CDSL",
        "INOXWIND": "INOWIN",
        "SUPREMEIND": "SUPIND",
        "ABCAPITAL": "ADBCAP",
        "NMDC": "NMDC",
        "AUROPHARMA": "AURPHA",
        "CGCL": "CAPGCO",
        "BOSCHLTD": "BOSCH",
        "WAAREEENER": "WAAREE",
        "RVNL": "RVNL",
        "AMBUJACEM": "AMBCEM",
        "OFSS": "ORAFIN",
        "ALKEM": "ALKLAB",
        "TATAPOWER": "TATPOW",
        "GVT&D": "GEP&D",
        "DELHIVERY": "DELHIV",
        "AUBANK": "AUBANK",
        "MOTILALOFS": "MOTWAL",
        "NYKAA": "FSNONT",
        "ZYDUSLIFE": "ZYDLIF",
        "JUBLFOOD": "JUBFOO",
        "BHARATFORG": "BHAFOR",
        "GODREJPROP": "GODPRO",
        "NEULANDLAB": "NEULAB",
        "GLAND": "GLAPHA",
        "MAZDOCK": "MAZDOCK",
        "TMCV": "TATMOT",
        "NH": "NARHRU",
        "DEVYANI": "DEVINT",
        "SYNGENE": "SYNGEN",
        "CANBK": "CANBK",
        "CESC": "CESC",
        "INDIANB": "INDIANB",
        "LALPATHLAB": "DRLAL",
        "PIDILITIND": "PIDIND",
        "TVSMOTOR": "TVSMOT",
        "WELCORP": "WELGUJ",
        "BAJAJFINSV": "BAJFNS",
        "OLAELEC": "OLAELE",
        "KEI": "KEIIND",
        "NUVAMA": "NUVAMA",
        "BANKINDIA": "BANIND",
        "SWIGGY": "SWIGGY",
        "HAVELLS": "HAVELL",
        "AEGISLOG": "AEGLOG",
        "M&MFIN": "MAHFAN",
        "NAVINFLUOR": "NAVFLU",
        "HSCL": "HIMSYS",
        "ICICIAMC": "ICIPRU",
        "PIIND": "PIIND",
        "BSE": "BSE",
        "ABB": "ABB",
        "JINDALSTEL": "JINSTE",
        "LODHA": "MACLOD",
        "COROMANDEL": "CORINT",
        "CHOLAHLDNG": "CHOHLD",
        "BIOCON": "BIOCON",
        "COHANCE": "SOLPHA",
        "SONACOMS": "SONCOM",
        "NHPC": "NHPC",
        "GLENMARK": "GLEPHA",
        "PAYTM": "ONE97",
        "GRASIM": "GRASIM",
        "BANKBARODA": "BANBAR",
        "SARDAEN": "SARENE",
        "JMFINANCIL": "JMFINA",
        "TATACAP": "TATCAP",
        "UNITDSPR": "UNISPI",
        "RBLBANK": "RBLBAN",
        "IKS": "IKSSOL",
        "STARHEALTH": "STAHEA",
        "INDIGO": "INTERA",
        "PWL": "POWGRI",
        "PGEL": "PGELEC",
        "HUDCO": "HUDCO",
        "ANANDRATHI": "ANARAT",
        "PRESTIGE": "PREEST",
        "IIFL": "IIFL",
        "ETERNAL": "ETERNAL",
        "ANANTRAJ": "ANARAJ",
        "MPHASIS": "MPHASI",
        "MEESHO": "MEESHO",
        "POONAWALLA": "POONAW",
        "BEL": "BEL",
        "TATACOMM": "TATCOM",
        "SHRIRAMFIN": "SHRUTI",
        "REDINGTON": "REDING",
        "JSWENERGY": "JSWENE",
        "JYOTICNC": "JYOCNC",
        "ABREL": "ADAREN"
    }

    @classmethod
    def to_breeze(cls, nse_symbol: str) -> str:
        """Converts NSE Symbol to Breeze Stock Code."""
        # Check explicit mapping first
        if nse_symbol in cls._NSE_TO_BREEZE:
            return cls._NSE_TO_BREEZE[nse_symbol]
        
        # Heuristic for symbols with &
        if "&" in nse_symbol:
            # Breeze often uses 'P&D' -> 'P&D' or replaces with '_'
            # But the specific GE T&D case is GEP&D
            return nse_symbol 
            
        return nse_symbol

    @classmethod
    def to_nse(cls, breeze_code: str) -> str:
        """Converts Breeze Stock Code back to NSE Symbol (Reverse lookup)."""
        for nse, breeze in cls._NSE_TO_BREEZE.items():
            if breeze == breeze_code:
                return nse
        return breeze_code
