GOAL_CATALOG = {
    "survival": [
        {"id": "emergency_fund", "name": "Emergency Fund", "icon": "🏦",
         "desc": "6–12 months of living expenses", "inflation": 0.06},
        {"id": "medical_emergency", "name": "Medical Emergency", "icon": "🏥",
         "desc": "Health contingency corpus", "inflation": 0.12},
        {"id": "job_loss_buffer", "name": "Job Loss Buffer", "icon": "🛡️",
         "desc": "12–24 months income safety net", "inflation": 0.06},
    ],
    "safety": [
        {"id": "retirement", "name": "Retirement", "icon": "🏖️",
         "desc": "25× annual expense rule", "inflation": 0.06},
        {"id": "home_purchase", "name": "Home Purchase", "icon": "🏠",
         "desc": "Down payment + registration", "inflation": 0.08},
        {"id": "children_education", "name": "Children's Education", "icon": "🎓",
         "desc": "10–12% education inflation", "inflation": 0.12},
        {"id": "parent_care", "name": "Parent Care", "icon": "👴",
         "desc": "Elder support & medical expenses", "inflation": 0.10},
        {"id": "debt_freedom", "name": "Debt Freedom", "icon": "⛓️",
         "desc": "Clear all high-interest liabilities", "inflation": 0.0},
    ],
    "growth": [
        {"id": "children_marriage", "name": "Children's Marriage", "icon": "💍",
         "desc": "₹25–50L inflation-adjusted", "inflation": 0.08},
        {"id": "travel", "name": "Travel & Experiences", "icon": "✈️",
         "desc": "Bucket-list travel fund", "inflation": 0.06},
        {"id": "real_estate", "name": "Real Estate", "icon": "🏢",
         "desc": "Second home or commercial property", "inflation": 0.08},
        {"id": "business", "name": "Start a Business", "icon": "🚀",
         "desc": "Seed capital for venture", "inflation": 0.07},
        {"id": "legacy", "name": "Legacy Gift", "icon": "🎁",
         "desc": "Wealth transfer to next generation", "inflation": 0.06},
        {"id": "philanthropy", "name": "Philanthropy", "icon": "🤝",
         "desc": "Charitable giving corpus", "inflation": 0.06},
        {"id": "esg_impact", "name": "ESG Impact", "icon": "🌱",
         "desc": "SEBI-compliant impact investing", "inflation": 0.06},
        {"id": "tax_optimise", "name": "Tax Optimisation", "icon": "📋",
         "desc": "ELSS, 80C, NPS maximisation", "inflation": 0.0},
        {"id": "wealth_creation", "name": "General Wealth", "icon": "📈",
         "desc": "Beat inflation by 4–6% CAGR", "inflation": 0.06},
    ]
}

QUICK_ADVICE_ALLOCATIONS = {
    ("Wealth Growth",        "Aggressive"):   {"Equities": 80, "Passive/ETF": 15, "Debt": 5},
    ("Wealth Growth",        "Moderate"):     {"Equities": 60, "Passive/ETF": 20, "Debt": 20},
    ("Wealth Growth",        "Conservative"): {"Equities": 40, "Passive/ETF": 20, "Debt": 40},
    ("Regular Income",       "Aggressive"):   {"Equities": 40, "Debt": 40, "REITs/InvIT": 20},
    ("Regular Income",       "Moderate"):     {"Equities": 20, "Debt": 60, "REITs/InvIT": 20},
    ("Regular Income",       "Conservative"): {"Debt": 70, "FD/GOI Bonds": 20, "Cash": 10},
    ("Tax Saving",           "Aggressive"):   {"ELSS": 80, "NPS Equity": 20},
    ("Tax Saving",           "Moderate"):     {"ELSS": 50, "NPS": 30, "PPF": 20},
    ("Tax Saving",           "Conservative"): {"PPF": 50, "NPS Debt": 30, "GOI Bonds": 20},
    ("Capital Preservation", "Aggressive"):   {"Debt": 50, "Equities": 30, "Gold": 20},
    ("Capital Preservation", "Moderate"):     {"Debt": 60, "Gold": 25, "Cash": 15},
    ("Capital Preservation", "Conservative"): {"Debt": 70, "Gold": 20, "Cash": 10},
}
